{{- $fullName := include "uname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullName | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ "root" | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullName | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  auth: {{ (print "root:{PLAIN}" (index .Values.auth.password)) | b64enc | quote }}
