sentinel:
  resources:
    requests:
      memory: 48Mi
    limits:
      memory: 64Mi

redis:
  resources:
    requests:
      memory: 384Mi
    limits:
      memory: 512Mi

haproxy:
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 128Mi

persistentVolume:
  size: 10Gi
